name: K6 Performance Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: |
            src/tests/report.html

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install k6 v1.2.2
        run: |
          K6_VERSION=1.2.2
          URL="https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-amd64.tar.gz"

          echo "Downloading $URL"
          curl -sLo k6.tar.gz "$URL"

          echo "Extracting..."
          tar -xzf k6.tar.gz
          sudo mv "k6-v${K6_VERSION}-linux-amd64/k6" /usr/local/bin/k6
          sudo chmod +x /usr/local/bin/k6
          rm -rf k6.tar.gz "k6-v${K6_VERSION}-linux-amd64"

          echo "k6 version:"
          k6 version

      - name: Run k6 tests
        run: |
          mkdir -p results
          npm run test:suite

          # Relat√≥rio HTML dentro de src/tests
          if [ -f relatorio.html ]; then
            mv relatorio.html results/
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: k6-results
          path: results

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: k6-results
          path: results
